"""Initial schema

Revision ID: bfa73f1adefc
Revises: 
Create Date: 2025-11-14 06:56:16.501541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa73f1adefc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(length=20), nullable=False),
    sa.Column('guild_name', sa.String(length=100), nullable=False),
    sa.Column('default_max_players', sa.Integer(), nullable=True),
    sa.Column('default_reminder_minutes', sa.JSON(), nullable=True),
    sa.Column('default_rules', sa.String(length=2000), nullable=True),
    sa.Column('allowed_host_role_ids', sa.JSON(), nullable=True),
    sa.Column('require_host_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_configurations_guild_id'), 'guild_configurations', ['guild_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discord_id', sa.String(length=20), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_table('channel_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(length=20), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('reminder_minutes', sa.JSON(), nullable=True),
    sa.Column('default_rules', sa.String(length=2000), nullable=True),
    sa.Column('allowed_host_role_ids', sa.JSON(), nullable=True),
    sa.Column('game_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_configurations_channel_id'), 'channel_configurations', ['channel_id'], unique=True)
    op.create_index(op.f('ix_channel_configurations_guild_id'), 'channel_configurations', ['guild_id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=20), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('reminder_minutes', sa.JSON(), nullable=True),
    sa.Column('rules', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='gamestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel_configurations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configurations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_channel_id'), 'game_sessions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_game_sessions_guild_id'), 'game_sessions', ['guild_id'], unique=False)
    op.create_index(op.f('ix_game_sessions_host_id'), 'game_sessions', ['host_id'], unique=False)
    op.create_index(op.f('ix_game_sessions_message_id'), 'game_sessions', ['message_id'], unique=False)
    op.create_index(op.f('ix_game_sessions_scheduled_at'), 'game_sessions', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_game_sessions_status'), 'game_sessions', ['status'], unique=False)
    op.create_table('game_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('JOINED', 'DROPPED', 'WAITLIST', 'PLACEHOLDER', name='participantstatus'), nullable=False),
    sa.Column('is_pre_populated', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(status = 'PLACEHOLDER' AND user_id IS NULL) OR (status != 'PLACEHOLDER' AND user_id IS NOT NULL)", name='placeholder_status_constraint'),
    sa.CheckConstraint('(user_id IS NOT NULL AND display_name IS NULL) OR (user_id IS NULL AND display_name IS NOT NULL)', name='user_or_placeholder_constraint'),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_participants_game_session_id'), 'game_participants', ['game_session_id'], unique=False)
    op.create_index(op.f('ix_game_participants_status'), 'game_participants', ['status'], unique=False)
    op.create_index(op.f('ix_game_participants_user_id'), 'game_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_participants_user_id'), table_name='game_participants')
    op.drop_index(op.f('ix_game_participants_status'), table_name='game_participants')
    op.drop_index(op.f('ix_game_participants_game_session_id'), table_name='game_participants')
    op.drop_table('game_participants')
    op.drop_index(op.f('ix_game_sessions_status'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_scheduled_at'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_message_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_host_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_guild_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_channel_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_channel_configurations_guild_id'), table_name='channel_configurations')
    op.drop_index(op.f('ix_channel_configurations_channel_id'), table_name='channel_configurations')
    op.drop_table('channel_configurations')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_guild_configurations_guild_id'), table_name='guild_configurations')
    op.drop_table('guild_configurations')
    # ### end Alembic commands ###
