# Copyright 2025-2026 Bret McKee
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


"""initial_schema

Revision ID: c2135ff3d5cd
Revises:
Create Date: 2025-12-16 13:49:51.274772

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2135ff3d5cd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_configurations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("guild_id", sa.String(length=20), nullable=False),
        sa.Column("bot_manager_role_ids", sa.JSON(), nullable=True),
        sa.Column(
            "require_host_role",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_guild_configurations_guild_id"),
        "guild_configurations",
        ["guild_id"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("discord_id", sa.String(length=20), nullable=False),
        sa.Column(
            "notification_preferences",
            sa.JSON(),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_discord_id"), "users", ["discord_id"], unique=True)
    op.create_table(
        "channel_configurations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("guild_id", sa.String(length=36), nullable=False),
        sa.Column("channel_id", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_configurations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_configurations_channel_id"),
        "channel_configurations",
        ["channel_id"],
        unique=True,
    )
    op.create_table(
        "game_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("guild_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("channel_id", sa.String(length=36), nullable=False),
        sa.Column("notify_role_ids", sa.JSON(), nullable=True),
        sa.Column("allowed_player_role_ids", sa.JSON(), nullable=True),
        sa.Column("allowed_host_role_ids", sa.JSON(), nullable=True),
        sa.Column("max_players", sa.Integer(), nullable=True),
        sa.Column("expected_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("reminder_minutes", sa.JSON(), nullable=True),
        sa.Column("where", sa.Text(), nullable=True),
        sa.Column("signup_instructions", sa.Text(), nullable=True),
        sa.CheckConstraint('"order" >= 0', name="ck_template_order_positive"),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel_configurations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_configurations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_game_templates_guild_default",
        "game_templates",
        ["guild_id", "is_default"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_templates_guild_id"), "game_templates", ["guild_id"], unique=False
    )
    op.create_index(
        "ix_game_templates_guild_order",
        "game_templates",
        ["guild_id", "order"],
        unique=False,
    )
    op.create_table(
        "game_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("template_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("signup_instructions", sa.Text(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("where", sa.Text(), nullable=True),
        sa.Column("max_players", sa.Integer(), nullable=True),
        sa.Column("guild_id", sa.String(length=36), nullable=False),
        sa.Column("channel_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=20), nullable=True),
        sa.Column("host_id", sa.String(length=36), nullable=False),
        sa.Column("reminder_minutes", sa.JSON(), nullable=True),
        sa.Column("notify_role_ids", sa.JSON(), nullable=True),
        sa.Column("allowed_player_role_ids", sa.JSON(), nullable=True),
        sa.Column("expected_duration_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'SCHEDULED'"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel_configurations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_configurations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["game_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_sessions_created_at"),
        "game_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_game_sessions_status"), "game_sessions", ["status"], unique=False)
    op.create_index(
        op.f("ix_game_sessions_template_id"),
        "game_sessions",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "game_participants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("game_session_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("joined_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("pre_filled_position", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(user_id IS NOT NULL AND display_name IS NULL) OR "
            "(user_id IS NULL AND display_name IS NOT NULL)",
            name="participant_identity_check",
        ),
        sa.ForeignKeyConstraint(["game_session_id"], ["game_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_session_id", "user_id", name="unique_game_participant"),
    )
    op.create_index(
        op.f("ix_game_participants_game_session_id"),
        "game_participants",
        ["game_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_participants_user_id"),
        "game_participants",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "game_status_schedule",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("game_id", sa.String(length=36), nullable=False),
        sa.Column("target_status", sa.String(length=20), nullable=False),
        sa.Column("transition_time", sa.DateTime(), nullable=False),
        sa.Column("executed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["game_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "target_status", name="uq_game_status_schedule_game_target"),
    )
    op.create_table(
        "notification_schedule",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("game_id", sa.String(length=36), nullable=False),
        sa.Column("reminder_minutes", sa.Integer(), nullable=False),
        sa.Column("notification_time", sa.DateTime(), nullable=False),
        sa.Column("game_scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("sent", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["game_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "game_id", "reminder_minutes", name="uq_notification_schedule_game_reminder"
        ),
    )
    op.create_index(
        op.f("ix_notification_schedule_game_id"),
        "notification_schedule",
        ["game_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_schedule_notification_time"),
        "notification_schedule",
        ["notification_time"],
        unique=False,
    )
    public_notify_schedule_changed = PGFunction(
        schema="public",
        signature="notify_schedule_changed()",
        definition=(
            "RETURNS TRIGGER AS $$\n"
            "    BEGIN\n"
            "        -- Only notify if change affects "
            "near-term schedule (within 10 minutes)\n"
            "        -- This reduces noise for distant future notifications\n"
            "        IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') AND\n"
            "           NEW.notification_time <= NOW() + INTERVAL '10 minutes' AND\n"
            "           NEW.sent = FALSE THEN\n"
            "            PERFORM pg_notify(\n"
            "                'notification_schedule_changed',\n"
            "                json_build_object(\n"
            "                    'operation', TG_OP,\n"
            "                    'game_id', NEW.game_id::text,\n"
            "                    'notification_time', NEW.notification_time::text\n"
            "                )::text\n"
            "            );\n"
            "        END IF;\n"
            "        RETURN NEW;\n"
            "    END;\n"
            "    $$ LANGUAGE plpgsql"
        ),
    )
    op.create_entity(public_notify_schedule_changed)

    public_notify_game_status_schedule_changed = PGFunction(
        schema="public",
        signature="notify_game_status_schedule_changed()",
        definition=(
            "RETURNS TRIGGER AS $$\n"
            "    BEGIN\n"
            "        -- Always notify on INSERT/UPDATE/DELETE "
            "so daemon can wake immediately\n"
            "        -- This enables true event-driven architecture without polling\n"
            "        IF TG_OP = 'DELETE' THEN\n"
            "            PERFORM pg_notify(\n"
            "                'game_status_schedule_changed',\n"
            "                json_build_object(\n"
            "                    'operation', TG_OP,\n"
            "                    'schedule_id', OLD.id::text,\n"
            "                    'game_id', OLD.game_id::text\n"
            "                )::text\n"
            "            );\n"
            "            RETURN OLD;\n"
            "        ELSE\n"
            "            -- INSERT or UPDATE\n"
            "            IF NEW.executed = FALSE THEN\n"
            "                PERFORM pg_notify(\n"
            "                    'game_status_schedule_changed',\n"
            "                    json_build_object(\n"
            "                        'operation', TG_OP,\n"
            "                        'schedule_id', NEW.id::text,\n"
            "                        'game_id', NEW.game_id::text,\n"
            "                        'transition_time', NEW.transition_time::text\n"
            "                    )::text\n"
            "                );\n"
            "            END IF;\n"
            "            RETURN NEW;\n"
            "        END IF;\n"
            "    END;\n"
            "    $$ LANGUAGE plpgsql"
        ),
    )
    op.create_entity(public_notify_game_status_schedule_changed)

    # Create triggers
    op.execute(
        sql_text(
            """
        CREATE TRIGGER notification_schedule_trigger
        AFTER INSERT OR UPDATE OR DELETE ON notification_schedule
        FOR EACH ROW
        EXECUTE FUNCTION notify_schedule_changed()
    """
        )
    )

    op.execute(
        sql_text(
            """
        CREATE TRIGGER game_status_schedule_trigger
        AFTER INSERT OR UPDATE OR DELETE ON game_status_schedule
        FOR EACH ROW
        EXECUTE FUNCTION notify_game_status_schedule_changed()
    """
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop triggers first
    op.execute(
        sql_text("DROP TRIGGER IF EXISTS game_status_schedule_trigger ON game_status_schedule")
    )
    op.execute(
        sql_text("DROP TRIGGER IF EXISTS notification_schedule_trigger ON notification_schedule")
    )

    public_notify_game_status_schedule_changed = PGFunction(
        schema="public",
        signature="notify_game_status_schedule_changed()",
        definition=(
            "RETURNS TRIGGER AS $$\n"
            "    BEGIN\n"
            "        -- Always notify on INSERT/UPDATE/DELETE "
            "so daemon can wake immediately\n"
            "        -- This enables true event-driven architecture without polling\n"
            "        IF TG_OP = 'DELETE' THEN\n"
            "            PERFORM pg_notify(\n"
            "                'game_status_schedule_changed',\n"
            "                json_build_object(\n"
            "                    'operation', TG_OP,\n"
            "                    'schedule_id', OLD.id::text,\n"
            "                    'game_id', OLD.game_id::text\n"
            "                )::text\n"
            "            );\n"
            "            RETURN OLD;\n"
            "        ELSE\n"
            "            -- INSERT or UPDATE\n"
            "            IF NEW.executed = FALSE THEN\n"
            "                PERFORM pg_notify(\n"
            "                    'game_status_schedule_changed',\n"
            "                    json_build_object(\n"
            "                        'operation', TG_OP,\n"
            "                        'schedule_id', NEW.id::text,\n"
            "                        'game_id', NEW.game_id::text,\n"
            "                        'transition_time', NEW.transition_time::text\n"
            "                    )::text\n"
            "                );\n"
            "            END IF;\n"
            "            RETURN NEW;\n"
            "        END IF;\n"
            "    END;\n"
            "    $$ LANGUAGE plpgsql"
        ),
    )
    op.drop_entity(public_notify_game_status_schedule_changed)

    public_notify_schedule_changed = PGFunction(
        schema="public",
        signature="notify_schedule_changed()",
        definition=(
            "RETURNS TRIGGER AS $$\n"
            "    BEGIN\n"
            "        -- Only notify if change affects "
            "near-term schedule (within 10 minutes)\n"
            "        -- This reduces noise for distant future notifications\n"
            "        IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') AND\n"
            "           NEW.notification_time <= NOW() + INTERVAL '10 minutes' AND\n"
            "           NEW.sent = FALSE THEN\n"
            "            PERFORM pg_notify(\n"
            "                'notification_schedule_changed',\n"
            "                json_build_object(\n"
            "                    'operation', TG_OP,\n"
            "                    'game_id', NEW.game_id::text,\n"
            "                    'notification_time', NEW.notification_time::text\n"
            "                )::text\n"
            "            );\n"
            "        END IF;\n"
            "        RETURN NEW;\n"
            "    END;\n"
            "    $$ LANGUAGE plpgsql"
        ),
    )
    op.drop_entity(public_notify_schedule_changed)

    op.drop_index(
        op.f("ix_notification_schedule_notification_time"),
        table_name="notification_schedule",
    )
    op.drop_index(op.f("ix_notification_schedule_game_id"), table_name="notification_schedule")
    op.drop_table("notification_schedule")
    op.drop_table("game_status_schedule")
    op.drop_index(op.f("ix_game_participants_user_id"), table_name="game_participants")
    op.drop_index(op.f("ix_game_participants_game_session_id"), table_name="game_participants")
    op.drop_table("game_participants")
    op.drop_index(op.f("ix_game_sessions_template_id"), table_name="game_sessions")
    op.drop_index(op.f("ix_game_sessions_status"), table_name="game_sessions")
    op.drop_index(op.f("ix_game_sessions_created_at"), table_name="game_sessions")
    op.drop_table("game_sessions")
    op.drop_index("ix_game_templates_guild_order", table_name="game_templates")
    op.drop_index(op.f("ix_game_templates_guild_id"), table_name="game_templates")
    op.drop_index("ix_game_templates_guild_default", table_name="game_templates")
    op.drop_table("game_templates")
    op.drop_index(
        op.f("ix_channel_configurations_channel_id"),
        table_name="channel_configurations",
    )
    op.drop_table("channel_configurations")
    op.drop_index(op.f("ix_users_discord_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_guild_configurations_guild_id"), table_name="guild_configurations")
    op.drop_table("guild_configurations")
    # ### end Alembic commands ###
